// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'atomic_operations_test.dart' as atomic_operations_test;
import 'inmemory_repository_test.dart' as inmemory_repository_test;
import 'offline_first_repository_test.dart' as offline_first_repository_test;
import 'remote_first_repository_test.dart' as remote_first_repository_test;
import 'restful_repository_test.dart' as restful_repository_test;

void main() {
  atomic_operations_test.main();
  remote_first_repository_test.main();
  offline_first_repository_test.main();
  inmemory_repository_test.main();
  restful_repository_test.main();
}
