name: example
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  http:
  data_connection_checker:
  repository:
    path: ../
  freezed_annotation:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  json_serializable:
  freezed:
  flutter_test:
    sdk: flutter

flutter:
